"""Auto-generated from companies.jsonl target_markets, business_model, NAICS labels."""

# markets=292 models=18 naics=105 total_hints=1074
CONTEXT_HINTS = frozenset({
    'administrative management and general management consulting services',
    'advanced technologies',
    'aged care',
    'ai-enabled hardware',
    'all other converted paper product manufacturing',
    'all other miscellaneous chemical product and preparation manufacturing',
    'all other miscellaneous electrical equipment and component manufacturing',
    'all other miscellaneous food manufacturing',
    'all other miscellaneous manufacturing',
    'all other plastics product manufacturing',
    'all other specialty trade contractors',
    'animal health',
    'apparel and footwear',
    'architectural services',
    'artificial intelligence',
    'asset management',
    'automobile and light duty motor vehicle manufacturing',
    'battery industry',
    'battery manufacturing',
    'battery materials',
    'battery technology',
    'beauty and cosmetics',
    'beauty and personal care',
    'biological product (except diagnostic) manufacturing',
    'bottled water manufacturing',
    'business services',
    'capital markets',
    'civic and social organizations',
    'civil and infrastructure',
    'clean energy',
    'cleantech & renewable energy',
    'clothing and clothing accessories retailers',
    'cloud computing',
    'cloud hosting',
    'coffee and tea manufacturing',
    'commercial and industrial machinery and equipment (except automotive and electronic) repair and maintenance',
    'commercial and institutional building construction',
    'commercial and service industry machinery manufacturing',
    'commercial development',
    'commercial vehicles',
    'commodity trading',
    'community development',
    'computer and network security',
    'computer systems design services',
    'computer vision',
    'computing infrastructure providers, data processing, web hosting, and related services',
    'construction machinery manufacturing',
    'consumer electronics',
    'consumer goods',
    'consumer health',
    'consumer packaged goods',
    'consumer products',
    'consumer services',
    'corporate/business services',
    'cosmetics and personal care',
    'crisis-affected regions',
    'cultural products',
    'custom computer programming services',
    'customer experience',
    'cut and sew apparel manufacturing (except contractors)',
    'data analysis',
    'data analytics',
    'data center services',
    'data centers',
    'data engineering',
    'data management',
    'data processing',
    'data science',
    'deep learning',
    'dental practices',
    'department stores',
    'digital services',
    'digital transformation',
    "drugs and druggists' sundries merchant wholesalers",
    'electric power distribution',
    'electrical and gas',
    'electrical apparatus and equipment, wiring supplies, and related equipment merchant wholesalers',
    'electrical contractors and other wiring installation contractors',
    'electrical engineering',
    'electronic computer manufacturing',
    'email marketing',
    'energy efficiency',
    'energy storage',
    'engineering services',
    'enterprise software',
    'entertainment and leisure',
    'environmental consulting',
    'environmental consulting services',
    'environmental protection',
    'environmental services',
    'estate and letting agents',
    'fabricated structural metal manufacturing',
    'farm supplies merchant wholesalers',
    'fats and oils refining and blending',
    'financial services',
    'financial transactions processing, reserve, and clearinghouse activities',
    'fitness and wellness',
    'food and beverage',
    'food processing',
    'fruit and vegetable canning',
    'general line grocery merchant wholesalers',
    'general warehousing and storage',
    'glass container manufacturing',
    'government services',
    'government/public sector',
    'green building',
    'grid storage',
    'hardware retailers',
    'health & beauty',
    'health & wellness',
    'health and wellness',
    'heating equipment (except warm air furnaces) manufacturing',
    'heavy manufacturing',
    'high tech',
    'highway, street, and bridge construction',
    'hobby, toy, and game retailers',
    'home centers',
    'home décor',
    'home goods',
    'home improvement',
    'household goods',
    'human resources',
    'human resources consulting services',
    'hydraulic oil',
    'in-vitro diagnostic substance manufacturing',
    'industrial automation',
    'industrial construction',
    'industrial manufacturing',
    'industrial supplies',
    'industrial supplies merchant wholesalers',
    'industrial truck, tractor, trailer, and stacker machinery manufacturing',
    'industry 4.0',
    'information technology',
    'international, secondary market, and all other nondepository credit intermediation',
    'involved in',
    'land use and resource management',
    'legal and accounting',
    'legal services',
    'life sciences',
    'lighting design',
    'lithium battery industry',
    'lithium-ion battery industry',
    'looking for',
    'luxury goods',
    'machine learning',
    'machine making',
    'marine and offshore',
    'marine bioeconomy',
    'marketing and communication',
    'mattress manufacturing',
    'meat processed from carcasses',
    'media and communications',
    'media and entertainment',
    'media and information services',
    'medical devices',
    'medicinal and botanical manufacturing',
    'military & commercial',
    'mining and metals',
    'miscellaneous financial investment activities',
    'motor vehicle gasoline engine and engine parts manufacturing',
    'music industry',
    'national security',
    'natural gas distribution',
    'natural gas extraction',
    'natural resources',
    'network technology',
    'neural networks',
    'new car dealers',
    'new energy',
    'new housing for-sale builders',
    'new materials',
    'nitrogenous fertilizer manufacturing',
    'non-profit organizations',
    'non-profit/non-governmental organization',
    'nonchocolate confectionery manufacturing',
    'off-grid energy',
    'office machinery and equipment rental and leasing',
    'office supplies',
    'offices of real estate agents and brokers',
    'oil & gas',
    'oil and gas',
    'other activities related to credit intermediation',
    'other basic inorganic chemical manufacturing',
    'other chemical and allied products merchant wholesalers',
    'other electronic parts and equipment merchant wholesalers',
    'other gasoline stations',
    'other heavy and civil engineering construction',
    'other management consulting services',
    'other paperboard container manufacturing',
    'other scientific and technical consulting services',
    'outdoor recreation',
    'paint and coating manufacturing',
    'payment processing',
    'payroll management',
    'payroll services',
    'personal care',
    'pet care',
    'petroleum and petroleum products merchant wholesalers (except bulk stations and terminals)',
    'petroleum refineries',
    'pharmaceutical preparation manufacturing',
    'pipelines & transmission',
    'plastics bottle manufacturing',
    'plastics pipe and pipe fitting manufacturing',
    'plumbing fixture fitting and trim manufacturing',
    'port and harbor operations',
    'portfolio management and investment advice',
    'postal service',
    'postal services',
    'power and communication line and related structures construction',
    'power generation',
    'power industry',
    'prefabricated metal building and component manufacturing',
    'printing and packaging',
    'private sector',
    'professional services',
    'project management',
    'public institutions',
    'public sector',
    'public services',
    'pulp and paper',
    'real estate',
    'real estate development',
    'record production and distribution',
    'recreational facilities',
    'regulated industries',
    'relay and industrial control manufacturing',
    'renewable energy',
    'research and development',
    'research and development in biotechnology (except nanobiotechnology)',
    'research and development in the physical, engineering, and life sciences (except nanotechnology and biotechnology)',
    'risk management',
    'robotics & industrial',
    'sales and marketing',
    'sanitary and medical-social',
    'searching for',
    'semiconductor and related device manufacturing',
    'service industries',
    'service provider',
    'small and medium-sized enterprises (smes)',
    'small business',
    'small businesses',
    'smart cities',
    'social services',
    'soft drink manufacturing',
    'software and digital platforms',
    'software development',
    'software publishers',
    'solar electric power generation',
    'soybean and other oilseed processing',
    'specialty canning',
    'specialty chemicals',
    'speech recognition',
    'speed changer, industrial high-speed drive, and gear manufacturing',
    'sporting goods retailers',
    'sports and recreation',
    'stationery product manufacturing',
    'supermarkets and other grocery retailers (except convenience retailers)',
    'supply chain',
    'support activities for rail transportation',
    'sustainable design',
    'sustainable development',
    'sustainable energy',
    'sustainable finance',
    'sustainable property renovation',
    'technology products and services',
    'theme parks',
    'toilet preparation manufacturing',
    'toys and games',
    'transport and logistics',
    'transportation and haulage',
    'travel and logistics',
    'turbine and turbine generator set units manufacturing',
    'urban development',
    'urban planning',
    'urban solutions',
    'vegetable oils',
    'vehicles & mobility',
    'veterinary practices',
    'warehouse clubs and supercenters',
    'water and wastewater',
    'water supply',
    'weather stations',
    'wellness and personal care',
    'what does',
    'who does',
    'wind electric power generation',
    'wine and spirits',
    'working on',
    'a-service',
    'a-services',
    'about',
    'abouts',
    'accessories',
    'accessory',
    'accounting',
    'accountings',
    'administrative',
    'administratives',
    'adtech',
    'adtechs',
    'advice',
    'advices',
    'aerospace',
    'aerospaces',
    'agricultural',
    'agriculturals',
    'agriculture',
    'agricultures',
    'agtech',
    'agtechs',
    'ai',
    'ai-enabled',
    'ai-enableds',
    'air',
    'analytic',
    'analytics',
    'animal',
    'animals',
    'apparel',
    'apparels',
    'aquaculture',
    'aquacultures',
    'architectural',
    'architecturals',
    'architecture',
    'architectures',
    'artificial',
    'artificials',
    'asset',
    'assets',
    'automation',
    'automations',
    'automobile',
    'automobiles',
    'automotive',
    'automotives',
    'aviation',
    'aviations',
    'banking',
    'bankings',
    'battery',
    'batterys',
    'beauty',
    'beautys',
    'beverage',
    'beverages',
    'bioeconomy',
    'bioeconomys',
    'biological',
    'biologicals',
    'biotechnology',
    'biotechnologys',
    'blending',
    'blendings',
    'botanical',
    'botanicals',
    'bottle',
    'bottled',
    'bottleds',
    'bottles',
    'bridge',
    'bridges',
    'bulk',
    'bulks',
    'business-to',
    'business-to-business',
    'business-to-businesss',
    'business-to-consumer',
    'business-to-consumers',
    'business-tos',
    'cannabi',
    'cannabis',
    'canning',
    'cannings',
    'capital',
    'capitals',
    'car',
    'carcasse',
    'carcasses',
    'cereal',
    'cereals',
    'chemical',
    'chemicals',
    'civic',
    'civics',
    'civil',
    'civils',
    'clean',
    'cleans',
    'cleantech',
    'cleantechs',
    'clearinghouse',
    'clearinghouses',
    'clothing',
    'clothings',
    'cloud',
    'clouds',
    'club',
    'clubs',
    'coating',
    'coatings',
    'coffee',
    'coffees',
    'commerce',
    'commerces',
    'commercial',
    'commercials',
    'commodity',
    'commoditys',
    'communication',
    'communications',
    'community',
    'communitys',
    'computer',
    'computers',
    'computing',
    'computings',
    'confectionery',
    'confectionerys',
    'construction',
    'constructions',
    'consulting',
    'consultings',
    'container',
    'containers',
    'contractor',
    'contractors',
    'control',
    'controls',
    'convenience',
    'conveniences',
    'converted',
    'converteds',
    'cor',
    'corporate',
    'corporates',
    'cosmetic',
    'cosmetics',
    'credit',
    'credits',
    'crisis-affected',
    'crisis-affecteds',
    'cultural',
    'culturals',
    'culture',
    'cultures',
    'customer',
    'customers',
    'cut',
    'cybersecurity',
    'cybersecuritys',
    'dealer',
    'dealers',
    'deep',
    'deeps',
    'defense',
    'defenses',
    'dental',
    'dentals',
    'department',
    'departments',
    'describe',
    'describes',
    'developer',
    'developers',
    'diagnostic',
    'diagnostics',
    'drainage',
    'drainages',
    'drink',
    'drinks',
    'drive',
    'drives',
    'drug',
    'druggist',
    'druggists',
    'drugs',
    'duty',
    'dutys',
    'e-commerce',
    'e-commerces',
    'education',
    'educations',
    'electric',
    'electrical',
    'electricals',
    'electrics',
    'electronic',
    'electronics',
    'email',
    'emails',
    'energy',
    'energys',
    'engine',
    'engineering',
    'engineerings',
    'engines',
    'enterprise',
    'enterprises',
    'entertainment',
    'entertainments',
    'environmental',
    'environmentals',
    'equipment',
    'equipments',
    'estate',
    'estates',
    'event',
    'events',
    'experience',
    'experiences',
    'extraction',
    'extractions',
    'fabricated',
    'fabricateds',
    'facilities',
    'farm',
    'farms',
    'fashion',
    'fashions',
    'fat',
    'fats',
    'fertilizer',
    'fertilizers',
    'finance',
    'finances',
    'financial',
    'financials',
    'fitness',
    'fitnesss',
    'fitting',
    'fittings',
    'fixture',
    'fixtures',
    'focused',
    'focuseds',
    'food',
    'foods',
    'footwear',
    'footwears',
    'for-sale',
    'for-sales',
    'forestry',
    'forestrys',
    'franchising',
    'franchisings',
    'fruit',
    'fruits',
    'furnace',
    'furnaces',
    'game',
    'games',
    'gaming',
    'gamings',
    'gas',
    'gasoline',
    'gasolines',
    'gear',
    'gears',
    'generation',
    'generations',
    'generator',
    'generators',
    'glass',
    'glasss',
    'government',
    'governments',
    'green',
    'greens',
    'grid',
    'grids',
    'grocery',
    'grocerys',
    'harbor',
    'harbors',
    'hardware',
    'hardwares',
    'haulage',
    'haulages',
    'health',
    'healthcare',
    'healthcares',
    'healths',
    'heating',
    'heatings',
    'heavy',
    'heavy-duty',
    'heavy-dutys',
    'heavys',
    'high-speed',
    'high-speeds',
    'highway',
    'highways',
    'hobby',
    'hobbys',
    'hospitality',
    'hospitalitys',
    'hosting',
    'hostings',
    'household',
    'households',
    'housing',
    'housings',
    'hr',
    'human',
    'humans',
    'hydraulic',
    'hydraulics',
    'hygiene',
    'hygienes',
    'improvement',
    'improvements',
    'in-vitro',
    'in-vitros',
    'industrial',
    'industrials',
    'industries',
    'industry',
    'industrys',
    'information',
    'informations',
    'infrastructure',
    'infrastructures',
    'inorganic',
    'inorganics',
    'institution',
    'institutional',
    'institutionals',
    'institutions',
    'insurance',
    'insurances',
    'intelligence',
    'intelligences',
    'intermediation',
    'intermediations',
    'investment',
    'investments',
    'it',
    'justice',
    'justices',
    'land',
    'lands',
    'learning',
    'learnings',
    'leasing',
    'leasings',
    'legal',
    'legals',
    'leisure',
    'leisures',
    'letting',
    'lettings',
    'licensing',
    'licensings',
    'life',
    'lifes',
    'light',
    'lighting',
    'lightings',
    'lights',
    'like',
    'likes',
    'line',
    'lines',
    'lithium',
    'lithium-ion',
    'lithium-ions',
    'lithiums',
    'lng',
    'logistic',
    'logistics',
    'logistics/transportation',
    'logistics/transportations',
    'luxury',
    'luxurys',
    'machine',
    'machinery',
    'machinerys',
    'machines',
    'making',
    'makings',
    'manufacturing',
    'manufacturings',
    'marine',
    'marines',
    'maritime',
    'maritimes',
    'market',
    'marketing',
    'marketings',
    'markets',
    'mattress',
    'mattresss',
    'meat',
    'meats',
    'media',
    'medias',
    'medical',
    'medical-social',
    'medical-socials',
    'medicals',
    'medicinal',
    'medicinals',
    'medium-sized',
    'medium-sizeds',
    'merchant',
    'merchants',
    'metal',
    'metals',
    'military',
    'militarys',
    'mining',
    'minings',
    'mobility',
    'mobilitys',
    'motor',
    'motors',
    'municipal',
    'municipals',
    'music',
    'musics',
    'nanobiotechnology',
    'nanobiotechnologys',
    'nanotechnology',
    'nanotechnologys',
    'national',
    'nationals',
    'natural',
    'naturals',
    'network',
    'networks',
    'neural',
    'neurals',
    'nitrogenou',
    'nitrogenous',
    'nlp',
    'non-governmental',
    'non-governmentals',
    'non-profit',
    'non-profits',
    'nonchocolate',
    'nonchocolates',
    'nondepository',
    'nondepositorys',
    'nonprofit',
    'nonprofits',
    'nuclear',
    'nuclears',
    'nutraceutical',
    'nutraceuticals',
    'nutrition',
    'nutritions',
    'off-grid',
    'off-grids',
    'offering',
    'offerings',
    'office',
    'offices',
    'offshore',
    'offshores',
    'oil',
    'oils',
    'oilseed',
    'oilseeds',
    'operation',
    'operations',
    'organization',
    'organizations',
    'outdoor',
    'outdoors',
    'packaged',
    'packageds',
    'packaging',
    'packagings',
    'paint',
    'paints',
    'paper',
    'paperboard',
    'paperboards',
    'papers',
    'park',
    'parks',
    'part',
    'parts',
    'payment',
    'payments',
    'payroll',
    'payrolls',
    'personal',
    'personals',
    'pet',
    'petrochemical',
    'petrochemicals',
    'petroleum',
    'petroleums',
    'pharmaceutical',
    'pharmaceuticals',
    'photography',
    'photographys',
    'physical',
    'physicals',
    'pipe',
    'pipeline',
    'pipelines',
    'pipes',
    'plastic',
    'plastics',
    'plumbing',
    'plumbings',
    'port',
    'portfolio',
    'portfolios',
    'ports',
    'postal',
    'postals',
    'power',
    'powers',
    'practice',
    'practices',
    'prefabricated',
    'prefabricateds',
    'printing',
    'printings',
    'private',
    'privates',
    'processed',
    'processeds',
    'professional',
    'professionals',
    'programming',
    'programmings',
    'property',
    'propertys',
    'protection',
    'protections',
    'public',
    'publics',
    'publisher',
    'publishers',
    'pulp',
    'pulps',
    'rail',
    'rails',
    'railway',
    'railways',
    'real',
    'reals',
    'recognition',
    'recognitions',
    'record',
    'records',
    'recreation',
    'recreational',
    'recreationals',
    'recreations',
    'refineries',
    'refinery',
    'refining',
    'refinings',
    'region',
    'regions',
    'regulated',
    'regulateds',
    'relay',
    'relays',
    'renewable',
    'renewables',
    'renovation',
    'renovations',
    'rental',
    'rentals',
    'repair',
    'repairs',
    'reserve',
    'reserves',
    'residential',
    'residentials',
    'resource',
    'resources',
    'retail',
    'retailer',
    'retailers',
    'retails',
    'risk',
    'risks',
    'robotic',
    'robotics',
    'sanitary',
    'sanitarys',
    'science',
    'sciences',
    'scientific',
    'scientifics',
    'sector',
    'sectors',
    'security',
    'securitys',
    'semiconductor',
    'semiconductors',
    'service',
    'services',
    'sew',
    'similar',
    'similars',
    'small',
    'smalls',
    'smart',
    'smarts',
    'sme',
    'smes',
    'social',
    'socials',
    'soft',
    'softs',
    'software',
    'software-a',
    'software-as',
    'software-as-a-service',
    'software-as-a-services',
    'softwares',
    'solar',
    'solars',
    'soybean',
    'soybeans',
    'space',
    'spaces',
    'specialising',
    'specialisings',
    'specialize',
    'specialized',
    'specializeds',
    'specializes',
    'specialty',
    'specialtys',
    'speech',
    'speechs',
    'speed',
    'speeds',
    'spirit',
    'spirits',
    'sport',
    'sporting',
    'sportings',
    'sports',
    'stacker',
    'stackers',
    'station',
    'stationery',
    'stationerys',
    'stations',
    'storage',
    'storages',
    'store',
    'stores',
    'street',
    'streets',
    'structural',
    'structurals',
    'structure',
    'structures',
    'subscription-based',
    'subscription-baseds',
    'substance',
    'substances',
    'sundries',
    'sundry',
    'supercenter',
    'supercenters',
    'supermarket',
    'supermarkets',
    'supplies',
    'supply',
    'supplys',
    'sustainability',
    'sustainabilitys',
    'sustainable',
    'sustainables',
    'tea',
    'tech',
    'technical',
    'technicals',
    'technology',
    'technologys',
    'techs',
    'telecom',
    'telecommunication',
    'telecommunications',
    'telecoms',
    'telework',
    'teleworks',
    'terminal',
    'terminals',
    'tertiary',
    'tertiarys',
    'theme',
    'themes',
    'tobacco',
    'tobaccos',
    'toilet',
    'toilets',
    'tourism',
    'tourisms',
    'toy',
    'toys',
    'tractor',
    'tractors',
    'trade',
    'trades',
    'trading',
    'tradings',
    'trailer',
    'trailers',
    'transaction',
    'transactions',
    'transformation',
    'transformations',
    'transmission',
    'transmissions',
    'transport',
    'transportation',
    'transportations',
    'transports',
    'travel',
    'travels',
    'trim',
    'trims',
    'truck',
    'trucks',
    'turbine',
    'turbines',
    'two-wheeler',
    'two-wheelers',
    'urban',
    'urbans',
    'utilities',
    'utility',
    'vegetable',
    'vegetables',
    'vehicle',
    'vehicles',
    'vertical',
    'verticals',
    'veterinary',
    'veterinarys',
    'vision',
    'visions',
    'vr',
    'warehouse',
    'warehouses',
    'warehousing',
    'warehousings',
    'warm',
    'warms',
    'wastewater',
    'wastewaters',
    'water',
    'waters',
    'weather',
    'weathers',
    'web',
    'wellness',
    'wellnesss',
    'wholesale',
    'wholesaler',
    'wholesalers',
    'wholesales',
    'wind',
    'winds',
    'wine',
    'wineries',
    'winery',
    'wines',
    'wiring',
    'wirings',
})
